spring.application.name=portfolio.performance.api
server.port:8082
# DataSource Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=portfolio_db;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=root

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect